# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3c2bb7d1805f7470b27bd45dc56e161f"
name = "remix-app-new"
handle = "remix-app-new-2"
application_url = "https://tsunami-fastest-weekends-modular.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "new-remix-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_orders,read_products,write_discounts,write_inventory,write_products"

[auth]
redirect_urls = [
  "https://tsunami-fastest-weekends-modular.trycloudflare.com/auth/callback",
  "https://tsunami-fastest-weekends-modular.trycloudflare.com/auth/shopify/callback",
  "https://tsunami-fastest-weekends-modular.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
